import { useState }  from 'react';
import { api }       from '@/lib/api';
import { toast }     from 'sonner';

/**
 * Returns { handleDownload, isDownloading }
 *
 * handleDownload(payslipId)
 *   - 200  → forces a browser file download via a hidden <a> element
 *   - 202  → shows a toast telling the user to try again shortly
 *   - 4xx/5xx → shows an error toast
 */
export function usePayslipDownload() {
  const [downloadingId, setDownloadingId] = useState<string | null>(null);

  const handleDownload = async (
    payslipId:    string,
    filenameHint: string   // e.g. "Payslip_March_2026.pdf"
  ) => {
    try {
      setDownloadingId(payslipId);

      const result = await api.getPayslipDownloadUrl(payslipId);

      // ── 202: PDF is still being generated by the background worker ──────
      if ('status' in result && result.status === 'processing') {
        toast.info('PDF is still being generated.', {
          description: 'Please try downloading again in a few moments.',
          duration:    5000,
        });
        return;
      }

      // ── 200: Force download via hidden anchor — avoids popup blockers ───
      // window.open() gets blocked; programmatic anchor click does not.
      const anchor       = document.createElement('a');
      anchor.href        = result.downloadUrl;
      anchor.download    = filenameHint;   // suggests filename to browser
      anchor.rel         = 'noopener noreferrer';
      anchor.style.display = 'none';

      document.body.appendChild(anchor);
      anchor.click();
      document.body.removeChild(anchor);

      toast.success('Download started.', {
        description: filenameHint,
        duration:    3000,
      });

    } catch (err) {
      toast.error('Failed to download payslip.', {
        description: err instanceof Error ? err.message : 'An unknown error occurred.',
        duration:    5000,
      });
    } finally {
      setDownloadingId(null);
    }
  };

  return {
    handleDownload,
    downloadingId,
    isDownloading: (id: string) => downloadingId === id,
  };
}