import { S3Client, GetObjectCommand } from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";
import Payslip from "../models/Payslip.models.js";
import "dotenv/config";

const s3Client = new S3Client({
  region: process.env.AWS_REGION,
  credentials: {
    accessKeyId: process.env.AWS_ACCESS_KEY_ID,
    secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
  },
});

const S3_BUCKET = process.env.AWS_S3_BUCKET_HR_PAYSLIPS;

export const getPayslipDownloadUrl = async (req, res) => {
  try {
    const { id: payslipId } = req.params;
    const userId = req.user.id;
    const userRole = req.user.role;
    const orgId = req.user.orgId;

    const payslip = await Payslip.findById(payslipId).lean();

    if (!payslip) {
      return res.status(404).json({ message: "Payslip not found." });
    }

    // tenant isolation
    if (payslip.orgId.toString() !== orgId.toString()) {
      return res
        .status(403)
        .json({ message: "Unauthorized to view this document." });
    }

    // RBAC — employee can only download their own; HR/admin can download any
    const isOwner = payslip.employeeId.toString() === userId.toString();
    const isHrOrAdmin = ["hr_manager", "super_admin"].includes(userRole);

    if (!isOwner && !isHrOrAdmin) {
      return res
        .status(403)
        .json({ message: "Unauthorized to view this document." });
    }

    // PDF not yet generated by the worker
    if (!payslip.s3Key) {
      return res.status(202).json({
        message: "PDF is currently being generated. Please try again shortly.",
        status: "processing",
      });
    }

    // — structured filename: Payslip_March_2026.pdf
    const monthLabel = new Date(
      payslip.payPeriod.year,
      payslip.payPeriod.month - 1,
      1,
    ).toLocaleString("en-US", { month: "long" });

    const command = new GetObjectCommand({
      Bucket: S3_BUCKET,
      Key: payslip.s3Key,
      ResponseContentDisposition: `attachment; filename="Payslip_${monthLabel}_${payslip.payPeriod.year}.pdf"`,
    });

    const signedUrl = await getSignedUrl(s3Client, command, { expiresIn: 60 });

    return res.status(200).json({
      message: "Download URL generated successfully.",
      downloadUrl: signedUrl,
    });
  } catch (error) {
    console.error("[getPayslipDownloadUrl] Error:", error.message);
    return res
      .status(500)
      .json({ message: "Failed to generate download link." });
  }
};
